server:
  port: 8080

spring:
  datasource:
    username: root
    password: Mn11037-
    url: jdbc:mysql://localhost:3306/easyloan?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver


#showSql
logging:
  level:
    com:
      example:
        mapper : debug