server:
  port: 9090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eroll?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: Mn11037-
  resources:
    static-locations: classpath:/templates  #访问静态页面